#!/usr/bin/env bash
#Bash script that stops 4-to_infinity_and_beyond process.


# Assuming the process name is 4-to_infinity_and_beyond
# You can replace it with the actual process name if needed
process_name="4-to_infinity_and_beyond"

# Use pkill to stop the process
pkill -f "$process_name"
