#!/usr/bin/env bash
# a lot of functions in one

process="/var/run/my_process.pid"

start () {
	./manage_my_process& echo $! > $process
}

stop () {
	if [ -e "$process" ]
	then
		pid=$(cat "$process")
		kill "$pid" && rm $process
	fi
}

case $1 in
	"start")start && echo "manage_my_process started";;
	"stop")stop && echo "manage_my_process stopped";;
	"restart")stop && start && echo "manage_my_process restarted";;
	*)echo "Usage: manage_my_process {start|stop|restart}";;
esac
