#!/usr/bin/env bash
#This script is displayng "Best School" 10 times, adding "Hi" on a new line 

count=0

while [ $count -lt 10 ]; do
	if [ $count -eq 8 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi

	((count++))
done
