#!/usr/bin/env bash
#displays the content of the current directory
#in list format where only the part of the name after
#the first dash is displayed

for FILENAME in *;
do
	echo "$FILENAME" | cut -d'-' -f2-
done
